def write_code(path, content, is_sql):
    content += "\n\n-- " \
        if is_sql \
        else "\n\n/** "
    content += "Generated by https://github.com/VictorAndres20/nest-backend-generator code generator for database, NestJS, React */"
    with open(path, "w") as f:
        f.write(content)
